### PR TITLE
ci: Add missing permissions required for SARIF upload

### PR DESCRIPTION
**Pull request by jamacku**
SARIF upload is failing due to missing permissions

```sh
❌ Failed to upload the SARIF report to GitHub
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 140.82.114.5:443...
* Connected to api.github.com (140.82.114.5) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS header, Certificate Status (22):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.2 (IN), TLS header, Finished (20):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2456 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [80 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.2 (OUT), TLS header, Finished (20):
} [5 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Mar 16 00:00:00 2022 GMT
*  expire date: Mar 16 23:59:59 2023 GMT
*  subjectAltName: host "api.github.com" matched cert's "*.github.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* h2h3 [:method: PUT]
* h2h3 [:path: /repos/jamacku/gha-prevent-big-files/code-scanning/analysis]
* h2h3 [:scheme: https]
* h2h3 [:authority: api.github.com]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [authorization: token ***]
* h2h3 [accept: application/vnd.github.v3+json]
* h2h3 [content-length: 518]
* h2h3 [content-type: application/x-www-form-urlencoded]
* Using Stream ID: 1 (easy handle 0x557527573460)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
> PUT /repos/jamacku/gha-prevent-big-files/code-scanning/analysis HTTP/2
> Host: api.github.com
> user-agent: curl/7.85.0
> authorization: token ***
> accept: application/vnd.github.v3+json
> content-length: 518
> content-type: application/x-www-form-urlencoded
> 
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* We are completely uploaded and fine
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
< HTTP/2 403 
< server: GitHub.com
< date: Tue, 17 Jan 2023 08:39:45 GMT
< content-type: application/json; charset=utf-8
< content-length: 113
< x-github-media-type: github.v3; format=json
< x-github-api-version-selected: 2022-11-28
< x-ratelimit-limit: 1000
< x-ratelimit-remaining: 997
< x-ratelimit-reset: 1673948228
< x-ratelimit-used: 3
< x-ratelimit-resource: code_scanning_upload
< access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
< access-control-allow-origin: *
< strict-transport-security: max-age=31536000; includeSubdomains; preload
< x-frame-options: deny
< x-content-type-options: nosniff
< x-xss-protection: 0
< referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
< content-security-policy: default-src 'none'
< vary: Accept-Encoding, Accept, X-Requested-With
< x-github-request-id: 4C80:7D78:613DA53:C86466F:63C65ED1
* The requested URL returned error: 403

 82   631    0     0  100   518      0   1628 --:--:-- --:--:-- --:--:--  1628
* Connection #0 to host api.github.com left intact
curl: (22) The requested URL returned error: 403
```

### CODE REVIEW

**Comment by james-callahan** [comment]
o.o @jamacku how did you come across this repo?

**Comment by jamacku** [comment]
This repository shows on the list of dependents of Differential ShellCheck GitHub Action.

**Comment by james-callahan** [comment]
I did a test of the current action config before merging, see https://github.com/james-callahan/gha-prevent-big-files/actions/runs/3935475784/jobs/6731184928 
image

Where/how are you seeing the error?

**Comment by jamacku** [comment]
I saw it in the last run in this repo:
- https://github.com/james-callahan/gha-prevent-big-files/actions/runs/3935697758/jobs/6731609652#step:4:31

**Comment by james-callahan** [comment]
huh.... any idea why it worked with my test earlier but not the latest run?

**Comment by jamacku** [comment]
It might also depend on your settings:

image

**Comment by james-callahan** [comment]
> It might also depend on your settings

I haven't changed those...

**Pull request merged**
